import { Card, CardContent } from "./ui/card";

const AnalysisContainer = () => {
  return (
    <Card className="flex-grow p-4 shadow-xl bg-white/90 backdrop-blur-lg">
      <CardContent className="text-center text-gray-700">
        <h2 className="text-lg font-semibold mb-2">Text Analysis</h2>
        <p className="text-sm">Generated by LLM</p>
      </CardContent>
    </Card>
  );
};

export default AnalysisContainer;
