import { Card, CardContent } from "./ui/card";

const AnalysisContainer = () => {
  return (
    <Card className="flex h-[70%] min-w-full mt-5 shadow-xl bg-white/90 backdrop-blur-lg section-background">
      <CardContent className="text-center text-white">
        <h2 className="text-lg font-semibold mb-2">Text Analysis</h2>
        <p className="text-sm">Generated by LLM</p>
      </CardContent>
    </Card>
  );
};

export default AnalysisContainer;
