[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs", "nodePackages.npm"]
cmds = [
  "chmod +x setup.sh",
  "./setup.sh"
]

[phases.build]
cmds = [
  "npm install --prefix dentai && npm run build --prefix dentai",
  "pip install -r requirements.txt"
]

[start]
cmd = "python backend/main.py"